version: '3'

services:
  app:
    container_name: app
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5000:5000
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: postgres:latest
    env_file:
      - /src/common/envs/.development.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: